# Generated by Django 4.0.5 on 2022-07-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='update_time',
            field=models.DateField(auto_now=True),
        ),
    ]
