# Generated by Django 4.0.5 on 2022-07-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
