# Generated by Django 4.0.5 on 2022-07-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
