# Generated by Django 4.0.5 on 2022-07-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('origin_note_id', models.IntegerField()),
                ('reference_note_id', models.IntegerField()),
            ],
        ),
    ]
