# Generated by Django 4.0.5 on 2022-07-04 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='owner_id',
            new_name='owner_id_FK',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='origin_note_id',
            new_name='ori_note_id',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='reference_note_id',
            new_name='ref_note_id',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='owner_id',
            new_name='owner_id_FK',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='note_id',
            new_name='note_id_FK',
        ),
    ]
