# Generated by Django 4.0.5 on 2022-07-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_rename_owner_id_image_owner_id_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='img_'),
        ),
    ]
